GET http://localhost:5000/mypage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNDFhYTM1ZC1lYWU0LTRiMGMtOWJmMC1mMDQ1MzdhZTY0MzAiLCJpYXQiOjE2MzMzNjg2OTAsImV4cCI6MTYzMzM2ODcwMH0.KBnoLHTdb0nBhH0L2aeMto1CN4DgNkFGLDdXl8o5nHo